### ISSUE TITLE
Create the section part "followers and followings"

### ISSUE THREAD

**Issue by AngelDiaz591** [AngelDiaz591/PI4_Foro_Web#53]
## REQUIREMENTS / DESCRIPTION

As a **project member**, I want to **design a section for managing followers and followings** so that **users can connect with each other and stay updated on their activities**.

### Design Goals:
- Enable users to follow other users and see their activities.
- Allow users to manage their followers and followings list.
- Provide notifications for new followers and updates from followed users.
- Ensure the design is intuitive and encourages user engagement.

### Proposed Design:
1. **Follow Button:**
   - Include a "Follow" button on user profiles and other relevant sections.
   - Display the number of followers and followings for each user.

2. **Followers and Followings Lists:**
   - Show a list of followers and followings for each user.
   - Include options to unfollow users and manage the list.

3. **Notifications:**
   - Notify users of new followers and activities from followed users.
   - Provide settings to customize notification preferences.

4. **User Profile Integration:**
   - Include followers and followings information on user profiles.
   - Allow users to see mutual followers and followings.

**Comment by Zama15** [comment]
yeah, that wont happen....
let me set up point 1 and 2, the others will increase the load of the PR, remember "divide and conquer", it is not necessary attack the problem entirely if it is big enoght
